// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

use std::collections::HashMap;
use std::env;

use module_info::get_module_info;
use nix::sys::signal::{raise, Signal};

module_info::embed!();

fn display_usage() {
    println!(
        r#"
CrashingProcess Example: a tool to generate different types of crashes.

This example demonstrates how module_info embeds metadata in binaries and
preserves it in crash dumps. The metadata can be inspected using:
    - readelf -n ./target/debug/examples/sample_crashing_process
    - strings ./target/debug/examples/sample_crashing_process | grep -A 10 "binary"

Usage:

    sample_crashing_process <command>

    <command> ::= {{ SIGABRT | SIGFPE | SIGILL | SIGINT | SIGSEGV | SIGTERM | EXCEPTION | INFO }}

        SIGABRT: (Signal Abort)
                    Abnormal termination, such as is initiated by the abort function.

        SIGFPE:  (Signal Floating-Point Exception)
                    Erroneous arithmetic operation, such as zero divide or an operation
                    resulting in overflow.

        SIGILL:  (Signal Illegal Instruction)
                    Invalid function image, such as an illegal instruction. This is generally
                    due to a corruption in the code or to an attempt to execute data.

        SIGINT:  (Signal Interrupt)
                    Interactive attention signal. Generally generated by the application user.

        SIGSEGV:  (Signal Segmentation Violation)
                    Invalid access to storage: When a program tries to read or write outside
                    the memory it is allocated for it.

        SIGTERM:  (Signal Terminate)
                    Termination request sent to program.

        EXCEPTION: Unhandled Exception

        INFO:      Display module info metadata
"#
    );
}

fn raise_signal(signal: Signal) {
    let _ = raise(signal);
}

fn longer_call_stack_func(signal: &str) -> Result<u32, std::io::Error> {
    function1(signal)
}

fn function1(signal: &str) -> Result<u32, std::io::Error> {
    function2(signal)
}

fn function2(signal: &str) -> Result<u32, std::io::Error> {
    function3(signal)
}

fn function3(signal: &str) -> Result<u32, std::io::Error> {
    helms_deep(signal)
}

fn helms_deep(signal: &str) -> Result<u32, std::io::Error> {
    // Adding a hashmap to make local call stack data a bit more complex
    let mut signal_handlers: HashMap<String, Box<dyn Fn()>> = HashMap::new();

    signal_handlers.insert(
        "SIGABRT".to_string(),
        Box::new(|| {
            raise_signal(Signal::SIGABRT);
        }),
    );

    signal_handlers.insert(
        "SIGFPE".to_string(),
        Box::new(|| {
            raise_signal(Signal::SIGFPE);
        }),
    );

    signal_handlers.insert(
        "SIGILL".to_string(),
        Box::new(|| {
            raise_signal(Signal::SIGILL);
        }),
    );

    signal_handlers.insert(
        "SIGINT".to_string(),
        Box::new(|| {
            raise_signal(Signal::SIGINT);
        }),
    );

    signal_handlers.insert(
        "SIGSEGV".to_string(),
        Box::new(|| {
            raise_signal(Signal::SIGSEGV);
        }),
    );

    signal_handlers.insert(
        "SIGTERM".to_string(),
        Box::new(|| {
            raise_signal(Signal::SIGTERM);
        }),
    );

    signal_handlers.insert(
        "EXCEPTION".to_string(),
        Box::new(|| {
            panic!("Unhandled exception");
        }),
    );

    signal_handlers.insert(
        "INFO".to_string(),
        Box::new(|| {
            println!("Module Information:");
            println!("------------------");

            match get_module_info!() {
                Ok(all_info) => {
                    for (key, value) in &all_info {
                        println!("{key}: {value}");
                    }
                }
                Err(e) => eprintln!("Failed to get module info: {e}"),
            }

            // Display individual fields using the enum approach
            println!("\nUsing field-specific retrieval:");
            if let Ok(binary) = get_module_info!(ModuleInfoField::Binary) {
                println!("Binary: {binary}");
            }
            if let Ok(version) = get_module_info!(ModuleInfoField::Version) {
                println!("Version: {version}");
            }
            if let Ok(module_version) = get_module_info!(ModuleInfoField::ModuleVersion) {
                println!("Module Version: {module_version}");
            }
            if let Ok(maintainer) = get_module_info!(ModuleInfoField::Maintainer) {
                println!("Maintainer: {maintainer}");
            }
        }),
    );

    if let Some(handler) = signal_handlers.get(signal) {
        handler();
    } else {
        println!(
            "Unknown signal: {}. Use one of: {}",
            signal,
            signal_handlers
                .keys()
                .cloned()
                .collect::<Vec<String>>()
                .join(", ")
        );
        display_usage();
    }

    Ok(signal_handlers.len() as u32)
}

fn main() -> Result<(), std::io::Error> {
    // Print module info at startup
    let _ = module_info::print_module_info();

    let args: Vec<String> = env::args().collect();

    let Some(command) = args.get(1) else {
        display_usage();
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            "Insufficient arguments provided",
        ));
    };

    let res = longer_call_stack_func(command.as_str());

    // This code will only execute if the signal doesn't cause a crash
    println!("Command execution result: {res:?}");

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Assert that `actual` has exactly `expected_parts` dot-separated
    /// components. Duplicated inline across several tests before; factoring
    /// here keeps the message format uniform and makes the "3-part version,
    /// 4-part module version" distinction a single point of maintenance.
    #[cfg(target_os = "linux")]
    fn assert_version_has_parts(actual: &str, expected_parts: usize, label: &str) {
        let actual_parts = actual.split('.').count();
        assert_eq!(
            actual_parts, expected_parts,
            "{label} {actual:?} should have {expected_parts} dot-separated parts, got {actual_parts}"
        );
    }

    #[cfg(target_os = "linux")]
    #[test]
    fn test_get_module_info_macro() {
        let binary = get_module_info!(ModuleInfoField::Binary)
            .expect("Failed to get binary name from module info");
        assert_eq!(binary, "sample_crashing_process");

        let version = get_module_info!(ModuleInfoField::Version)
            .expect("Failed to get version from module info");
        assert_version_has_parts(&version, 3, "version");

        let module_version = get_module_info!(ModuleInfoField::ModuleVersion)
            .expect("Failed to get module version from module info");
        assert_version_has_parts(&module_version, 4, "module version");

        let maintainer = get_module_info!(ModuleInfoField::Maintainer)
            .expect("Failed to get maintainer from module info");
        assert_eq!(maintainer, "example@contoso.com");

        let name =
            get_module_info!(ModuleInfoField::Name).expect("Failed to get name from module info");
        assert_eq!(name, "sample_crashing_process");

        let module_type =
            get_module_info!(ModuleInfoField::Type).expect("Failed to get type from module info");
        assert_eq!(module_type, "tool");

        let copyright = get_module_info!(ModuleInfoField::Copyright)
            .expect("Failed to get copyright from module info");
        assert_eq!(copyright, "Contoso, Ltd.");
    }

    #[cfg(target_os = "linux")]
    #[test]
    fn test_get_all_module_info() {
        let info = get_module_info!().expect("Failed to get module info HashMap");

        for (key, value) in &info {
            println!("{key}: {value}");
        }

        // Verify the HashMap contains the expected keys
        assert!(info.contains_key("binary"));
        assert!(info.contains_key("version"));
        assert!(info.contains_key("moduleVersion"));
        assert!(info.contains_key("maintainer"));
        assert!(info.contains_key("name"));
        assert!(info.contains_key("type"));
        assert!(info.contains_key("copyright"));
        assert!(info.contains_key("os"));
        assert!(info.contains_key("osVersion"));

        // Verify some values match what we expect
        assert_eq!(
            info.get("binary")
                .expect("Binary field should exist in module info HashMap"),
            "sample_crashing_process"
        );
        assert_eq!(
            info.get("name")
                .expect("Name field should exist in module info HashMap"),
            "sample_crashing_process"
        );
        assert_eq!(
            info.get("maintainer")
                .expect("Maintainer field should exist in module info HashMap"),
            "example@contoso.com"
        );
        assert_eq!(
            info.get("copyright")
                .expect("Copyright field should exist in module info HashMap"),
            "Contoso, Ltd."
        );
        assert_eq!(
            info.get("type")
                .expect("Type field should exist in module info HashMap"),
            "tool"
        );
        assert!(info.contains_key("os"));
        assert!(info.contains_key("osVersion"));
    }

    #[cfg(target_os = "linux")]
    #[test]
    fn test_module_info_comprehensive() {
        println!("Module Info Comprehensive Test");
        println!("-----------------------------");

        // Example of getting binary name using the enum
        match get_module_info!(ModuleInfoField::Binary) {
            Ok(binary) => {
                println!("Binary: {binary}");
                assert_eq!(binary, "sample_crashing_process");
            }
            Err(e) => {
                println!("Could not get binary name: {e}");
                panic!("Failed to get binary name: {e}");
            }
        }

        // Example of getting version using the enum
        match get_module_info!(ModuleInfoField::Version) {
            Ok(version) => {
                println!("Version: {version}");
                assert_version_has_parts(&version, 3, "version");
            }
            Err(e) => {
                println!("Could not get version: {e}");
                panic!("Failed to get version: {e}");
            }
        }
        // Example of getting maintainer using the enum
        match get_module_info!(ModuleInfoField::Maintainer) {
            Ok(maintainer) => {
                println!("Maintainer: {maintainer}");
                assert_eq!(maintainer, "example@contoso.com");
            }
            Err(e) => {
                println!("Could not get maintainer: {e}");
                panic!("Failed to get maintainer: {e}");
            }
        }

        // Example of getting module version using the enum
        match get_module_info!(ModuleInfoField::ModuleVersion) {
            Ok(module_version) => {
                println!("Module Version: {module_version}");
                assert_version_has_parts(&module_version, 4, "module version");
            }
            Err(e) => {
                println!("Could not get module version: {e}");
                panic!("Failed to get module version: {e}");
            }
        }

        // Example of getting all module info at once
        println!("\nUsing no-args approach to get all fields:");
        let all_info = get_module_info!().expect("Failed to get module info HashMap");

        // Print all values for debugging
        for (key, value) in &all_info {
            println!("{key}: {value}");
        }

        // Verify we have expected fields in the all_info map
        assert!(all_info.contains_key("binary"), "Missing 'binary' field");
        assert!(all_info.contains_key("version"), "Missing 'version' field");
        assert!(
            all_info.contains_key("moduleVersion"),
            "Missing 'moduleVersion' field"
        );
        assert!(
            all_info.contains_key("maintainer"),
            "Missing 'maintainer' field"
        );
        assert!(
            all_info.contains_key("copyright"),
            "Missing 'copyright' field"
        );
        assert!(all_info.contains_key("type"), "Missing 'type' field");
    }

    #[test]
    fn test_module_info_platform_specific() {
        println!("Module Info Platform-Specific Test");
        println!("---------------------------------");

        // On Linux, we expect successful retrieval
        #[cfg(target_os = "linux")]
        {
            let binary = get_module_info!(ModuleInfoField::Binary)
                .expect("Failed to get binary name on Linux platform");
            assert_eq!(binary, "sample_crashing_process");
        }

        #[cfg(not(target_os = "linux"))]
        {
            match get_module_info!(ModuleInfoField::Binary) {
                Ok::<String, module_info::ModuleInfoError>(_) => {
                    panic!("Expected error on non-Linux platform")
                }
                Err(e) => {
                    if let module_info::ModuleInfoError::NotAvailable(_) = e {
                        // This is the expected error
                        println!("Correctly received NotAvailable error on Windows: {:?}", e);
                        assert!(
                            matches!(e, module_info::ModuleInfoError::NotAvailable(_)),
                            "Error should be NotAvailable on non-Linux platforms"
                        );
                    } else {
                        panic!("Expected NotAvailable error, got: {e:?}");
                    }
                }
            }
        }
    }

    #[cfg(target_os = "linux")]
    #[test]
    fn test_git_info_fields() {
        println!("Testing Git info fields");
        println!("-----------------------");

        let info = get_module_info!().expect("Failed to get module info HashMap");

        if let Some(branch) = info.get("branch") {
            println!("Branch: {branch}");
            assert!(!branch.is_empty());
        }

        if let Some(hash) = info.get("hash") {
            println!("Commit Hash: {hash}");
            assert!(!hash.is_empty());
        }

        if let Some(repo) = info.get("repo") {
            println!("Repository: {repo}");
            assert!(!repo.is_empty());
        }
    }
}
